### ISSUE TITLE
Usage with Bootstrap Carousel

### ISSUE THREAD

**Issue by HybridSolutions** [greenish/jquery-cover#2]
Trying to use your plugin with Bootstrap Carousel but only the first image is getting correct. All the others do not stretch to fill the container. Any known workaround?

Since the images used in the carousel have the same width and height, Is there any way for the plugin to receive that info using parameters so that they can be applied to the other images without recalculate.

**Comment by ph101pp** [comment]
So it's not online anywhere? If not, .zip it up and send it to [removed]. I'll have a look at it!
